name: ml
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - pillow
  - pip
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu124
    - torch
    - torchvision
    - transformers
    - datasets
    - accelerate
    - evaluate
    - wandb
    - polars
    - duckdb
    - plotly
    - kaleido
    - optuna
    - kagglehub
    - albumentations
    - opencv-python-headless
